audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Cathy Naiser
  title:
  license_number:
  about_markdown: |
    The Naiser Real Estate Group is a small group very dedicated real estate agents and operations personnel lead by Cathy Naiser. We work with Sellers and Buyers and believe that excellent customer service comes from using the best technology and providing the best personal attention. Cathy Naiser has been professionally serving the community in Education and then in Real Estate for over 25 years. After graduation from college, Cathy entered the Convent and became a Catholic Nun. Simultaneously, she began her professional career as a middle school band director. While she remained in the convent for only 4 years, she taught school for 20 years. Most of those years were spent teaching in San Antonio, Texas After 20 years in the teaching profession, Cathy retired early. She studied real estate investing and began “flipping houses”. She became quite proficient in the real estate investing arena while flipping 23 houses in a 12-month period. In addition to wholesaling houses, she rehabbed houses, purchased rental properties, sold houses “owner financed” and sold notes on houses. During that time, she became a licensed real estate agent. She used her license to help her find and evaluate potential investment properties. Later, she joined Keller Williams and worked to become one of the Top Agents in the company. Her knowledge of real estate throughout the city was vast, and she attracted many buyers, sellers and investors. For 10 years, she has served on the Agent Leadership Council and the Faculty at Keller Williams Realty City View. Because of her high production and service to the community Cathy was named one of the city’s “Platinum Top 50” agent winners for 9 years in a row. She enjoy offering money saving programs to her clients and helping them reach their goals. Her mission is in Real Estate and Life to learn and grow and be the best she can be while positively influencing others and helping them move forward to their goals.
  brand: The Naiser Real Estate Group
  brokerage: Keller Williams Realty City View
  market: San Antonio
  address: 10999 IH 10 W ste 175 San Antonio, TX 78230
  phone: 210-844-6434
  phone_type:
  phone2:
  phone2_type:
  email: clients@mysanantoniomove.com
  url: https://MySanAntonioMove.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: https://cnaiser.kw.com/search

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://cnaiser.kw.com/search

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/CathyNaiserGroup/
  linkedin_url: https://www.linkedin.com/in/cathynaiser
  youtube_url: https://www.youtube.com/channel/UCICsfOTL7zIbRSyzHaWIu4A?view_as=subscriber
  twitter_url: https://cnaiser.kw.com/www.twitter.com/satxhouses
  instagram_url: https://www.instagram.com/cathynaiser/?hl=en
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#AC2828'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
